/**********************************************************************************************************************
 * \file App_Cpu0.c
 * \copyright Copyright (C) Infineon Technologies AG 2023
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"
#include "Port/Io/IfxPort_Io.h"
#include "App_Config.h"

#include <stdint.h>
#include <stdbool.h>
/*********************************************************************************************************************/
/*-----------------------------------------------------Macros--------------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

uint32_t cpu0_init_count = 0;
uint32_t cpu0_1ms_count = 0;
uint32_t cpu0_10ms_count = 0;
uint32_t cpu0_100ms_count = 0;
uint32_t cpu0_1000ms_count = 0;

/* Global flag variables */
volatile bool LED1_ENABLE_FLAG = false;
volatile bool LED2_ENABLE_FLAG = false;
volatile bool LED2_BLINK_FLAG = false;

/* CPU1/CPU2 looping counters */
volatile uint32_t cpu1_loop_count = 0;
volatile uint32_t cpu2_loop_count = 0;

/* Sequential execution control variables */
volatile bool CPU1_EXECUTION_READY = false;
volatile bool CPU1_EXECUTION_COMPLETE = false;
volatile bool CPU2_EXECUTION_READY = false;
volatile bool CPU2_EXECUTION_COMPLETE = false;
volatile bool LED_PROCESS_ACTIVE = false;
volatile uint32_t cpu1_cpu2_sequence_count = 0;

/* Button state variables for CPU0 task */
static IfxPort_State previous_button_state = IfxPort_State_high;
static uint32_t button_debounce_counter = 0;

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* CPU0 initialization task that runs at 1ms */
void task_cpu0_init(void *arg)
{
    while (1)
    {
        /* Increment init task counter */
        cpu0_init_count++;
        
        /* Wait for CPU0 init semaphore */
        //if (xSemaphoreTake(g_cpu0InitSem, portMAX_DELAY) == pdTRUE)
        //{
        
        /* Setup the port/pin connected to LED2 as general push-pull output
         * Purpose: Configure LED2 pin (P00.6) as output to control LED state
         */
         IfxPort_setPinMode(LED_2.port, LED_2.pinIndex, IfxPort_Mode_outputPushPullGeneral);

         /* Turn off LED2 initially (LED is active low)
          * Purpose: Ensure LED2 starts in known OFF state during system initialization
          */
         IfxPort_setPinState(LED_2.port, LED_2.pinIndex, IfxPort_State_high);
         
         /* Initialize BUTTON0 pin for CPU0 button handling */
         IfxPort_setPinMode(BUTTON_0.port, BUTTON_0.pinIndex, IfxPort_Mode_inputPullUp);
         
         /* Initialize LED1 pin for CPU0 LED1 control */
         IfxPort_setPinMode(LED_1.port, LED_1.pinIndex, IfxPort_Mode_outputPushPullGeneral);
         IfxPort_setPinState(LED_1.port, LED_1.pinIndex, IfxPort_State_high);
         
         /* Initialize balanced sequential execution control */
         LED_PROCESS_ACTIVE = false;        /* Process starts inactive */
         CPU1_EXECUTION_READY = false;      /* CPU1 not ready initially */
         CPU1_EXECUTION_COMPLETE = false;   /* CPU1 not completed initially */
         CPU2_EXECUTION_READY = false;      /* CPU2 not ready initially */
         CPU2_EXECUTION_COMPLETE = false;   /* CPU2 not completed initially */
         cpu1_cpu2_sequence_count = 0;      /* Reset sequence counter */

        //}
        
        /* Run at 1ms interval */
        vTaskDelay(pdMS_TO_TICKS(1));
    }
}

/* CPU0 1ms placeholder task */
void task_cpu0_1ms(void *arg)
{
    while (1)
    {
        /* Wait for CPU0 tick semaphore */
        //if (xSemaphoreTake(g_cpu0TickSem, portMAX_DELAY) == pdTRUE)
        //{
            /* Placeholder for 1ms task functionality */
            cpu0_1ms_count++;
            /* Give semaphore back before finishing */
            //xSemaphoreGive(g_cpu0TickSem);
        //}
        
        /* Task period: 1ms */
        vTaskDelay(pdMS_TO_TICKS(1));
    }
}

/* CPU0 10ms task - Button handling moved here */
void task_cpu0_10ms(void *arg)
{
    while (1)
    {
        /* Wait for CPU0 tick semaphore */
        //if (xSemaphoreTake(g_cpu0TickSem, portMAX_DELAY) == pdTRUE)
        //{
            /* 10ms task functionality */
            cpu0_10ms_count++;
            
            /* Button handling - call app function */
            app_cpu0_button();
            
            /* Give semaphore back before finishing */
            //xSemaphoreGive(g_cpu0TickSem);
        //}
        
        /* Task period: 10ms */
        vTaskDelay(pdMS_TO_TICKS(10));
    }
}

/* CPU0 100ms placeholder task */
void task_cpu0_100ms(void *arg)
{
    while (1)
    {
        /* Wait for CPU0 tick semaphore */
        //if (xSemaphoreTake(g_cpu0TickSem, portMAX_DELAY) == pdTRUE)
        //{
            /* Placeholder for 100ms task functionality */
            cpu0_100ms_count++;
            /* Give semaphore back before finishing */
            //xSemaphoreGive(g_cpu0TickSem);
        //}
        
        /* Task period: 100ms */
        vTaskDelay(pdMS_TO_TICKS(100));
    }
}

/* CPU0 1000ms task - Button functionality */
void task_cpu0_1000ms(void *arg)
{
    while (1)
    {
        /* Wait for CPU0 tick semaphore */
        //if (xSemaphoreTake(g_cpu0TickSem, portMAX_DELAY) == pdTRUE)
        //{
            cpu0_1000ms_count++;

            /* Toggle LED1 and LED2 state */
            app_cpu0_led1();
            app_cpu0_led2();
            
            /* Give semaphore back before finishing */
            //xSemaphoreGive(g_cpu0TickSem);
        //}
        
        /* Task period: 1000ms */
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}

/* Required FreeRTOS callback for CPU0, called in case of a stack overflow */
void vApplicationStackOverflowHook_CPU0(TaskHandle_t xTask, char *pcTaskName)
{
    while (1)
    {
        __nop();
    }
}

/* Toggle LED1 based on enable flag */
void app_cpu0_led1(void)
{
    if (LED1_ENABLE_FLAG)
    {
        IfxPort_setPinState(LED_1.port, LED_1.pinIndex, IfxPort_State_toggled);
    }
}

/* Toggle LED2 based on enable flag */
void app_cpu0_led2(void)
{
    if (LED2_ENABLE_FLAG)
    {
        IfxPort_setPinState(LED_2.port, LED_2.pinIndex, IfxPort_State_toggled);
    }
}

/* Button handling function */
void app_cpu0_button(void)
{
    IfxPort_State current_button_state = IfxPort_getPinState(BUTTON_0.port, BUTTON_0.pinIndex);
    
    /* Button debouncing logic */
    if (current_button_state == IfxPort_State_low && previous_button_state == IfxPort_State_high)
    {
        button_debounce_counter = 1;
    }
    else if (current_button_state == IfxPort_State_low && button_debounce_counter > 0)
    {
        button_debounce_counter++;
        if (button_debounce_counter >= BUTTON_DEBOUNCE_COUNT)
        {
            /* Button press confirmed - start LED process from CPU1 */
            if (!LED_PROCESS_ACTIVE)
            {
                /* Start LED process: CPU1 first, then CPU2 */
                LED_PROCESS_ACTIVE = true;
                CPU1_EXECUTION_READY = true;       /* Enable CPU1 to start */
                CPU1_EXECUTION_COMPLETE = false;
                CPU2_EXECUTION_READY = false;      /* CPU2 waits for CPU1 */
                CPU2_EXECUTION_COMPLETE = false;
            }
            else
            {
                /* Stop LED process - will complete at CPU2 (LED OFF) */
                LED_PROCESS_ACTIVE = false;
            }
            button_debounce_counter = 0;
        }
    }
    else if (current_button_state == IfxPort_State_high)
    {
        button_debounce_counter = 0;
    }
    
    previous_button_state = current_button_state;
}
