/**********************************************************************************************************************
 * \file App_Cpu2.c
 * \copyright Copyright (C) Infineon Technologies AG 2023
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#define FREERTOS_CONFIG_H_INCLUDE_GUARD
#include "Configurations/FreeRTOSConfig_CPU2.h"
#undef FREERTOS_CONFIG_H_INCLUDE_GUARD

#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"
#include "Port/Io/IfxPort_Io.h"
#include "App_Config.h"

/*********************************************************************************************************************/
/*-----------------------------------------------------Macros--------------------------------------------------------*/
/*********************************************************************************************************************/
/* Configuration macros are now defined in App_Config.h for centralized management */

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/


/* CPU2 initialization task that runs at 1ms */
void task_cpu2_init(void *arg)
{
    /* Wait for CPU2 initialization semaphore before proceeding */
    if (xSemaphoreTake(g_cpu2InitSem, portMAX_DELAY) == pdTRUE)
    {
        /* Setup the port/pin connected to LED2 as general push-pull output
         * Purpose: Configure LED2 pin (P00.6) as output to control LED state
         */
        IfxPort_setPinMode(LED_2.port, LED_2.pinIndex, IfxPort_Mode_outputPushPullGeneral);

        /* Turn off LED2 initially (LED is active low)
         * Purpose: Ensure LED2 starts in known OFF state during system initialization
         */
        IfxPort_setPinState(LED_2.port, LED_2.pinIndex, IfxPort_State_high);
    }
    
    while (1)
    {
        /* Wait for CPU2 init semaphore */
        if (xSemaphoreTake(g_cpu2InitSem, portMAX_DELAY) == pdTRUE)
        {
            /* Give CPU2 tick semaphore to allow other tasks to proceed */
            if (g_cpu2TickSem != NULL)
            {
                xSemaphoreGive(g_cpu2TickSem);
            }
        }
        
        /* Run at 1ms interval */
        vTaskDelay(pdMS_TO_TICKS(1));
    }
}

/* CPU2 1ms placeholder task */
void task_cpu2_1ms(void *arg)
{
    while (1)
    {
        /* Wait for CPU2 tick semaphore */
        if (xSemaphoreTake(g_cpu2TickSem, portMAX_DELAY) == pdTRUE)
        {
            /* Placeholder for 1ms task functionality */
            
            /* Give semaphore back before finishing */
            xSemaphoreGive(g_cpu2TickSem);
        }
        
        /* Task period: 1ms */
        vTaskDelay(pdMS_TO_TICKS(1));
    }
}

/* CPU2 10ms placeholder task */
void task_cpu2_10ms(void *arg)
{
    while (1)
    {
        /* Wait for CPU2 tick semaphore */
        if (xSemaphoreTake(g_cpu2TickSem, portMAX_DELAY) == pdTRUE)
        {
            /* Placeholder for 10ms task functionality */
            
            /* Give semaphore back before finishing */
            xSemaphoreGive(g_cpu2TickSem);
        }
        
        /* Task period: 10ms */
        vTaskDelay(pdMS_TO_TICKS(10));
    }
}

/* CPU2 100ms placeholder task */
void task_cpu2_100ms(void *arg)
{
    while (1)
    {
        /* Wait for CPU2 tick semaphore */
        if (xSemaphoreTake(g_cpu2TickSem, portMAX_DELAY) == pdTRUE)
        {
            /* Placeholder for 100ms task functionality */
            
            /* Give semaphore back before finishing */
            xSemaphoreGive(g_cpu2TickSem);
        }
        
        /* Task period: 100ms */
        vTaskDelay(pdMS_TO_TICKS(100));
    }
}

/* CPU2 1000ms task - LED2 functionality */
void task_cpu2_1000ms(void *arg)
{
    while (1)
    {
        /* Wait for CPU2 tick semaphore */
        if (xSemaphoreTake(g_cpu2TickSem, portMAX_DELAY) == pdTRUE)
        {
            /* Toggle LED2 state */
            app_cpu2_led();
            
            /* Give semaphore back before finishing */
            xSemaphoreGive(g_cpu2TickSem);
        }
        
        /* Task period: 1000ms */
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}

/* Required FreeRTOS callback for CPU2, called in case of a stack overflow */
void vApplicationStackOverflowHook_CPU2(TaskHandle_t xTask, char *pcTaskName)
{
    while (1)
    {
        __nop();
    }
}

/* Toggle LED2 based on enable flag */
void app_cpu2_led(void)
{
    if (LED2_ENABLE_FLAG)
    {
        IfxPort_setPinState(LED_2.port, LED_2.pinIndex, IfxPort_State_toggled);
    }
}