/**********************************************************************************************************************
 * \file App_Cpu1_Logic.c
 * \copyright Copyright (C) Infineon Technologies AG 2023
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Port/Io/IfxPort_Io.h"
#include "App_Config.h"
#include <stdint.h>
#include <stdbool.h>

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
extern uint32_t cpu1_tick_counter;

/* CPU1 LED2 ON control with symmetric flag checking */
void app_cpu1_led2on(void)
{
    /* CPU1 LED2 ON control with balanced state management */
    if ((cpu1_tick_counter % 100000) == 0)
    {
        cpu1_tick_counter++;
        
        /* CPU1 execution conditions: LED process active AND CPU1 ready AND CPU2 not complete */
        if (LED_PROCESS_ACTIVE && CPU1_EXECUTION_READY && !CPU2_EXECUTION_COMPLETE)
        {
            /* Pre-execution state management */
            CPU1_EXECUTION_READY = false;      /* Reset CPU1 ready flag */
            CPU1_EXECUTION_COMPLETE = false;   /* Reset CPU1 completion flag */
            
            /* CPU1 main execution: Turn LED2 ON */
            IfxPort_setPinState(LED_2.port, LED_2.pinIndex, IfxPort_State_low);
            cpu1_loop_count++;
            
            /* Post-execution state management */
            CPU1_EXECUTION_COMPLETE = true;    /* Signal CPU1 has completed */
            CPU2_EXECUTION_READY = true;       /* Enable CPU2 to start */
            cpu1_cpu2_sequence_count++;        /* Track successful sequences */
        }
        
        /* CPU1 monitoring: Reset flags when CPU2 completes */
        if (CPU2_EXECUTION_COMPLETE)
        {
            CPU2_EXECUTION_COMPLETE = false;   /* Reset CPU2 completion flag */
            if (LED_PROCESS_ACTIVE)
            {
                CPU1_EXECUTION_READY = true;   /* Ready for next cycle */
            }
        }
    }
}