/**********************************************************************************************************************
 * \file App_Cpu2_Comm.c
 * \copyright Copyright (C) Infineon Technologies AG 2023
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Port/Io/IfxPort_Io.h"
#include "App_Config.h"
#include <stdint.h>
#include <stdbool.h>

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
extern uint32_t cpu2_tick_count;

/* CPU2 communication logic - now empty, all app logic moved to CPU0 */
void app_cpu2_led2off(void)
{
    /* CPU2 LED2 OFF control with balanced state management */
    if ((cpu2_tick_count % 100000) == 0)
    {
        cpu2_tick_count++;
        
        /* CPU2 execution conditions: CPU2 ready AND CPU1 complete AND CPU1 not ready */
        if (CPU2_EXECUTION_READY && CPU1_EXECUTION_COMPLETE && !CPU1_EXECUTION_READY)
        {
            /* Pre-execution state management */
            CPU2_EXECUTION_READY = false;      /* Reset CPU2 ready flag */
            CPU2_EXECUTION_COMPLETE = false;   /* Reset CPU2 completion flag */
            
            /* CPU2 main execution: Always turn LED2 OFF */
            IfxPort_setPinState(LED_2.port, LED_2.pinIndex, IfxPort_State_high);
            cpu2_loop_count++;
            
            /* Post-execution state management */
            CPU2_EXECUTION_COMPLETE = true;    /* Signal CPU2 has completed */
            CPU1_EXECUTION_COMPLETE = false;   /* Reset CPU1 completion flag */
        }
        
        /* CPU2 monitoring: Reset flags when CPU1 completes */
        if (CPU1_EXECUTION_COMPLETE)
        {
            CPU1_EXECUTION_COMPLETE = false;   /* Reset CPU1 completion flag */
            if (LED_PROCESS_ACTIVE)
            {
                CPU2_EXECUTION_READY = true;   /* Ready for next cycle */
            }
        }
        
        /* CPU2 idle state: Monitor for process state changes */
        if (!LED_PROCESS_ACTIVE && !CPU1_EXECUTION_COMPLETE)
        {
            /* Ensure flags are reset when process is inactive */
            CPU2_EXECUTION_READY = false;
            CPU2_EXECUTION_COMPLETE = false;
        }
    }
}
