/**********************************************************************************************************************
 * \file App_Config.h
 * \copyright Copyright (C) Infineon Technologies AG 2023
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef APP_CONFIG_H_
#define APP_CONFIG_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxPort_PinMap.h"
#include "Port/Io/IfxPort_Io.h"
#include "FreeRTOS.h"
#include "semphr.h"

#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

/*********************************************************************************************************************/
/*--------------------------------------------- Generic System Setup -----------------------------------------------*/
/*********************************************************************************************************************/

/* Hardware Pin Definitions */
#define BUTTON_0                IfxPort_P00_7       /* Port/Pin for BUTTON 0 - Monitored by CPU0                    */
#define LED_1                   IfxPort_P00_5       /* Port/Pin for LED 1 - Controlled by CPU1                      */
#define LED_2                   IfxPort_P00_6       /* Port/Pin for LED 2 - Controlled by CPU2                      */

/* Global Synchronization Objects */
extern SemaphoreHandle_t g_cpu0InitSem;            /* Binary semaphore for CPU0 initialization synchronization    */
extern SemaphoreHandle_t g_cpu0TickSem;            /* Counting semaphore for CPU0 task tick synchronization       */
extern SemaphoreHandle_t g_cpu1InitSem;            /* Binary semaphore for CPU1 initialization synchronization    */
extern SemaphoreHandle_t g_cpu1TickSem;            /* Counting semaphore for CPU1 task tick synchronization       */
extern SemaphoreHandle_t g_cpu2InitSem;            /* Binary semaphore for CPU2 initialization synchronization    */
extern SemaphoreHandle_t g_cpu2TickSem;            /* Counting semaphore for CPU2 task tick synchronization       */

/* System-wide Configuration */
#define BUTTON_DEBOUNCE_COUNT   (5)                /* Number of consecutive readings for debouncing                */

/* System-wide Boolean Flags */
extern volatile bool LED1_ENABLE_FLAG;
extern volatile bool LED2_ENABLE_FLAG;

/*********************************************************************************************************************/
/*------------------------------------------------- CPU0 Section ---------------------------------------------------*/
/*********************************************************************************************************************/
/* Function prototypes */
void app_cpu0_led(void);

/* CPU0 Task Functions */
void task_cpu0_init(void *arg);                    /* CPU0 initialization task running at 1ms                     */
void task_cpu0_1ms(void *arg);                     /* CPU0 1ms placeholder task                                    */
void task_cpu0_10ms(void *arg);                    /* CPU0 10ms placeholder task                                   */
void task_cpu0_100ms(void *arg);                   /* CPU0 100ms placeholder task                                  */
void task_cpu0_1000ms(void *arg);                  /* CPU0 1000ms placeholder task                                 */


/* CPU0 Configuration */
#define CPU0_INIT_TASK_PRIORITY     (2)            /* Priority for CPU0 init task                                  */
#define CPU0_INIT_TASK_STACK        (configMINIMAL_STACK_SIZE)  /* Stack size for CPU0 init task            */
#define CPU0_1MS_TASK_PRIORITY      (3)            /* Priority for CPU0 1ms task                                   */
#define CPU0_1MS_TASK_STACK         (configMINIMAL_STACK_SIZE)  /* Stack size for CPU0 1ms task             */
#define CPU0_10MS_TASK_PRIORITY     (4)            /* Priority for CPU0 10ms task                                  */
#define CPU0_10MS_TASK_STACK        (configMINIMAL_STACK_SIZE)  /* Stack size for CPU0 10ms task            */
#define CPU0_100MS_TASK_PRIORITY    (5)            /* Priority for CPU0 100ms task                                 */
#define CPU0_100MS_TASK_STACK       (configMINIMAL_STACK_SIZE)  /* Stack size for CPU0 100ms task           */
#define CPU0_1000MS_TASK_PRIORITY   (6)            /* Priority for CPU0 1000ms task                                */
#define CPU0_1000MS_TASK_STACK      (configMINIMAL_STACK_SIZE)  /* Stack size for CPU0 1000ms task          */

/*********************************************************************************************************************/
/*------------------------------------------------- CPU1 Section ---------------------------------------------------*/
/*********************************************************************************************************************/

/* Function prototypes */
void app_cpu1_led(void);


/* CPU1 Task Functions */
void task_cpu1_init(void *arg);                    /* CPU1 initialization task running at 1ms                     */
void task_cpu1_1ms(void *arg);                     /* CPU1 1ms placeholder task                                    */
void task_cpu1_10ms(void *arg);                    /* CPU1 10ms placeholder task                                   */
void task_cpu1_100ms(void *arg);                   /* CPU1 100ms placeholder task                                  */
void task_cpu1_1000ms(void *arg);                  /* CPU1 1000ms placeholder task                                 */

/* CPU1 Configuration */
#define CPU1_INIT_TASK_PRIORITY     (2)            /* Priority for CPU1 init task                                  */
#define CPU1_INIT_TASK_STACK        (configMINIMAL_STACK_SIZE)  /* Stack size for CPU1 init task            */
#define CPU1_1MS_TASK_PRIORITY      (3)            /* Priority for CPU1 1ms task                                   */
#define CPU1_1MS_TASK_STACK         (configMINIMAL_STACK_SIZE)  /* Stack size for CPU1 1ms task             */
#define CPU1_10MS_TASK_PRIORITY     (4)            /* Priority for CPU1 10ms task                                  */
#define CPU1_10MS_TASK_STACK        (configMINIMAL_STACK_SIZE)  /* Stack size for CPU1 10ms task            */
#define CPU1_100MS_TASK_PRIORITY    (5)            /* Priority for CPU1 100ms task                                 */
#define CPU1_100MS_TASK_STACK       (configMINIMAL_STACK_SIZE)  /* Stack size for CPU1 100ms task           */
#define CPU1_1000MS_TASK_PRIORITY   (6)            /* Priority for CPU1 1000ms task                                */
#define CPU1_1000MS_TASK_STACK      (configMINIMAL_STACK_SIZE)  /* Stack size for CPU1 1000ms task          */

/*********************************************************************************************************************/
/*------------------------------------------------- CPU2 Section ---------------------------------------------------*/
/*********************************************************************************************************************/
/* Function prototypes */
void app_cpu2_button(void);

/* CPU2 Task Functions */
void task_cpu2_init(void *arg);                    /* CPU2 initialization task running at 1ms                     */
void task_cpu2_1ms(void *arg);                     /* CPU2 1ms placeholder task                                    */
void task_cpu2_10ms(void *arg);                    /* CPU2 10ms placeholder task                                   */
void task_cpu2_100ms(void *arg);                   /* CPU2 100ms placeholder task                                  */
void task_cpu2_1000ms(void *arg);                  /* CPU2 1000ms placeholder task                                 */

/* CPU2 Configuration */
#define CPU2_INIT_TASK_PRIORITY     (2)            /* Priority for CPU2 init task                                  */
#define CPU2_INIT_TASK_STACK        (configMINIMAL_STACK_SIZE)  /* Stack size for CPU2 init task            */
#define CPU2_1MS_TASK_PRIORITY      (3)            /* Priority for CPU2 1ms task                                   */
#define CPU2_1MS_TASK_STACK         (configMINIMAL_STACK_SIZE)  /* Stack size for CPU2 1ms task             */
#define CPU2_10MS_TASK_PRIORITY     (4)            /* Priority for CPU2 10ms task                                  */
#define CPU2_10MS_TASK_STACK        (configMINIMAL_STACK_SIZE)  /* Stack size for CPU2 10ms task            */
#define CPU2_100MS_TASK_PRIORITY    (5)            /* Priority for CPU2 100ms task                                 */
#define CPU2_100MS_TASK_STACK       (configMINIMAL_STACK_SIZE)  /* Stack size for CPU2 100ms task           */
#define CPU2_1000MS_TASK_PRIORITY   (6)            /* Priority for CPU2 1000ms task                                */
#define CPU2_1000MS_TASK_STACK      (configMINIMAL_STACK_SIZE)  /* Stack size for CPU2 1000ms task          */

#endif /* APP_CONFIG_H_ */
