/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
  *********************************************************************************************************************/
 /*\title TC375 FreeRTOS basic example
 * \abstract This example shows how to get started with using the AURIX(TM) FreeRTOS port
 * \description This example explores FreeRTOS usage on AURIX(TM) TC375 using two simple tasks and one interrupt
 *
 * \name iLLD_TC375_ADS_FreeRTOS_Basic
 * \version V1.0.0
 * \board AURIX TC375 lite Kit, KIT_A2G_TC375_LITE, TC37xTP_A-Step
 * \keywords AURIX, TC3XX, TC375, FreeRTOS, Blinky, Task, ERU, LED, Button, External Interrupt
 * \documents See README.md
 * \lastUpdated 2023-04-27
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "App_Config.h"
#include "FreeRTOS.h"
#include "task.h"

/* CPU core main function declarations */
extern void core1_main(void);
extern void core2_main(void);

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

uint8_t cpu0_main_count = 0;

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    cpu0_main_count++; //Step No. 1

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    cpu0_main_count++; //Step No. 2

    /* Create init semaphores for each CPU0 */
    g_cpu0InitSem = xSemaphoreCreateBinary();
    g_cpu0TickSem = xSemaphoreCreateBinary();

    cpu0_main_count++; //Step No. 3

    /* Make each init semaphore available exactly once */
    xSemaphoreGive(g_cpu0InitSem);
    

    cpu0_main_count++; //Step No. 4


    /* Create init task on CPU0 */
    xTaskCreate(task_cpu0_init, "INIT CPU0", CPU0_INIT_TASK_STACK, NULL, CPU0_INIT_TASK_PRIORITY, NULL);
    
    cpu0_main_count++; //Step No. 5

    /* Create placeholder tasks on CPU0 */
    xTaskCreate(task_cpu0_1ms, "CPU0 1MS", CPU0_1MS_TASK_STACK, NULL, CPU0_1MS_TASK_PRIORITY, NULL);
    xTaskCreate(task_cpu0_10ms, "CPU0 10MS", CPU0_10MS_TASK_STACK, NULL, CPU0_10MS_TASK_PRIORITY, NULL);
    xTaskCreate(task_cpu0_100ms, "CPU0 100MS", CPU0_100MS_TASK_STACK, NULL, CPU0_100MS_TASK_PRIORITY, NULL);
    xTaskCreate(task_cpu0_1000ms, "CPU0 1000MS", CPU0_1000MS_TASK_STACK, NULL, CPU0_1000MS_TASK_PRIORITY, NULL);
    
    cpu0_main_count++; //Step No. 6

    /* Start CPU1 and CPU2 */
    IfxCpu_startCore(&MODULE_CPU1, (uint32)core1_main);
    IfxCpu_startCore(&MODULE_CPU2, (uint32)core2_main);

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 3);  /* Wait for all 3 CPUs */
    
    cpu0_main_count++; //Step No. 7

    /* Start the scheduler */
    vTaskStartScheduler();
    
    cpu0_main_count++; //Step No. 8

    /* Should never reach here if scheduler starts successfully */
    while (1)
    {
        cpu0_main_count++; //Step No. 9
        __nop();
    }
}

/* Required FreeRTOS callback, called in case of a stack overflow.
 * For the sake of simplicity, this function will loop indefinitely
 * and the root cause can be confirmed by using a debugger
 */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    while (1)
    {
        __nop();
    }
}
