/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

/* Include CPU2 specific FreeRTOS configuration */
#define FREERTOS_CONFIG_H_INCLUDE_GUARD
#include "FreeRTOSConfig2.h"
#undef FREERTOS_CONFIG_H_INCLUDE_GUARD

#include "FreeRTOS.h"
#include "task.h"
#include "App_Config.h"

extern IfxCpu_syncEvent g_cpuSyncEvent;

void core2_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG2 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    /* Create init task on CPU2 */
    xTaskCreate(task_cpu2_init, "INIT CPU2", CPU2_INIT_TASK_STACK, NULL, CPU2_INIT_TASK_PRIORITY, NULL);
    
    /* Create placeholder tasks on CPU2 */
    xTaskCreate(task_cpu2_1ms, "CPU2 1MS", CPU2_1MS_TASK_STACK, NULL, CPU2_1MS_TASK_PRIORITY, NULL);
    xTaskCreate(task_cpu2_10ms, "CPU2 10MS", CPU2_10MS_TASK_STACK, NULL, CPU2_10MS_TASK_PRIORITY, NULL);
    xTaskCreate(task_cpu2_100ms, "CPU2 100MS", CPU2_100MS_TASK_STACK, NULL, CPU2_100MS_TASK_PRIORITY, NULL);
    xTaskCreate(task_cpu2_1000ms, "CPU2 1000MS", CPU2_1000MS_TASK_STACK, NULL, CPU2_1000MS_TASK_PRIORITY, NULL);
    
    /* Start the FreeRTOS scheduler on CPU2 */
    vTaskStartScheduler();
    
    /* Should never reach here if scheduler starts successfully */
    while(1)
    {
        __nop();
    }
}

/* Required FreeRTOS callback for CPU2, called in case of a stack overflow */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    while (1)
    {
        __nop();
    }
}
